### ISSUE TITLE
Fall back strategy for headerless PDB files.

### ISSUE THREAD

**Issue by OWissett** [douweschulte/pdbtbx#122]
I have been working with a bunch of PDB files without a header, and found that the identifier isn't parsed since that comes from the HEADER records.

A work around I have is to fallback to using the file name. I think this should be added to the library, since it makes sense to load the identifier from the file name, as you may have multiple different versions of a pdb file with the same HEADER record too. 

We can add this to the `ReadOptions` struct.

**Comment by douweschulte** [comment]
Sounds like a good plan. To be sure I understand you correctly is it the goal to make the fallback, if there is no header use the file name, default behaviour and make renaming to the file name an option for `ReadOptions`? That sounds perfect to me. Although a bit of CA should be given to the raw parse methods, because they maybe do not need this fallback support to prevent breaking any existing code where a filename is not obviously available.

**Comment by OWissett** [comment]
#123 I think this issue is essentially a more extreme version of this issue.
